version: '3.9'

services:
  webinterface:
    build: app
    container_name: elearning-app
    hostname: app
    volumes:
      - ./app:/app
    depends_on:
      - mainapi
    ports:
      - 8080:8080
    environment:
      NODE_APP: elearning-interface
      NODE_ENV: development
    networks:
      - elearningnet

  mainapi:
    build: main-api
    container_name: elearning-mainapi
    hostname: api
    volumes:
      - ./main-api:/api
      - ./data/files:/files
    depends_on:
      - mongo
      - usersapi
      - statisticsapi
    ports:
      - 5000:5000
    networks:
      - elearningnet

  usersapi:
    build: users-api
    container_name: elearning-usersapi
    hostname: users
    volumes:
      - ./users-api:/api
    depends_on:
      - sql
    networks:
      - elearningnet

  statisticsapi:
    build: statistics-api
    container_name: elearning-statisticsapi
    hostname: statistics
    environment:
      FLASK_APP: app
      FLASK_HOST: 0.0.0.0
      FLASK_ENV: development
    volumes:
      - ./statistics-api:/api
    networks:
      - elearningnet

  sql:
    build: sql
    container_name: elearning-sql
    hostname: sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elearning
    volumes:
      - ./data/sql:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elearningnet

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: elearning-mongo-express
    environment:
      ME_CONFIG_MONGODB_OPTIONS_EDITORTHEME: "dracula"
      ME_CONFIG_MONDODB_URL: mongodb://dbuser:dbpass@mongo:27017
      ME_CONFIG_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    depends_on:
      - mongo
    networks:
      - elearningnet

  mongo:
    build: mongo
    container_name: elearning-mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: elearning
    volumes:
      - ./data/mongo:/data/db
    networks:
      - elearningnet

networks:
  elearningnet:
    name: elearningnet
