version: '3.9'

services:
  sql:
    build: sql
    hostname: sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elearning
    volumes:
      - ./data/sql:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbnet

  mongo:
    image: mongo:5.0
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: elearning
    volumes:
      - ./data/mongo:/data/db
    networks:
      - dbnet

  redis:
    image: redis:6.0-alpine3.15
    hostname: redis
    networks:
      - dbnet

networks:
  dbnet:
    name: dbnet