version: '3.9'

services:
  sql:
    build: sql
    hostname: sql
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: elearning
    volumes:
      - ./data/sql:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbnet

  mongoexpress:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_OPTIONS_EDITORTHEME: "dracula"
      ME_CONFIG_MONDODB_URL: mongodb://dbuser:dbpass@mongo:27017
      ME_CONFIG_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbpass
    depends_on:
      - mongo
    networks:
      - dbnet

  mongo:
    build: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: elearning
    volumes:
      - ./data/mongo:/data/db
    networks:
      - dbnet

  redis:
    image: redis:6.0-alpine3.15
    hostname: redis
    networks:
      - dbnet

networks:
  dbnet:
    name: dbnet